--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/WarpUI
projects:
  WarpUI:
    path: ""
    libs:
      - src: thebigsmilexd/customui/customui
        version: ^3.0.0
      - src: CortexPE/Commando/Commando
        version: ^0.3.1
...
